---
- hosts: all
  become: yes
  tasks:
  -  name: Install apache2
     apt:
       name: apache2
       update_cache: yes
       state: present


# sudo apt-get update
# sudo apt-get install apache2
# service apache2 restart